export const SET_CURRENCY_DATA = 'SET_CURRENCY_DATA';
export const GET_CURRENCY_DATA = 'GET_CURRENCY_DATA';

export const SET_FIRST_CURRENCY = 'SET_FIRST_CURRENCY';
export const SET_FIRST_VALUE = 'SET_FIRST_VALUE';
export const SET_SECOND_CURRENCY = 'SET_SECOND_CURRENCY';
export const SET_SECOND_VALUE = 'SET_SECOND_VALUE';
export const SET_INITIAL_DATA = 'SET_INITIAL_DATA';
